### ISSUE TITLE
I was curious if this was a virus

### ISSUE THREAD

**Issue by DevBaccon** [Gwyd0/Sparx-bwk#10]
so i tried it on a vm it worked but i was skectipal that it maybe be dangerous and ran it on virus total 
![image](https://github.com/Gwyd0/Sparx-bwk/assets/85125377/c32b9ea9-b396-49d2-967f-62fe055e830b)
can someone explain

**Comment by Matapakka** [comment]
wait so is it a virus or na

**Comment by DevBaccon** [comment]
idk maybe it is maybe its not

**Comment by DevBaccon** [comment]
idk maybe or not

**Comment by NajmAjmal-old** [comment]
Hi, 

If you want to use a Virus-FREE Open source program.

You can use [Sintco Sparxmaths Solver](https://github.com/SintcoLTD/sparxmaths). I also run it through [VirusTotal](https://www.virustotal.com/gui/file/a95bd651eb24a2738ab6ced3c6588c78a78f5d26cbacbad469cea4908a1048a8?nocache=1) and it came back like this

![image](https://github.com/Gwyd0/Sparx-bwk/assets/130285427/be0afaa2-0686-4efd-8292-890ec3375968)

This program is Virus free. and ALL Code is available to your viewing. This program is a Chrom/Edge/OperaGX Extension and it works on ALL Browsers with inspect

Try out Sintco Sparxmaths Solver here:
https://github.com/SintcoLTD/sparxmaths

**Comment by DevBaccon** [comment]
the only thing it really does is not write bookwork codes which is fine by me

**Comment by NajmAjmal-old** [comment]
Hi,

This Automatically stores bookwork codes and during the book work check it highlights the correct answer.

![](https://raw.githubusercontent.com/SintcoLTD/CDN/main/chrome-extension/sparxmaths/images/bookwork-code.png)

Also, it has 9 different Colour themes.

https://github.com/SintcoLTD/sparxmaths

**Comment by Gwyd0** [comment]
**Sparx Bwk** is not a virus although windows sometimes may warn of a virus when running the **.exe**

**Comment by NajmAjmal-old** [comment]
Hi @Gwyd0,

What do you mean by **“windows sometimes may warn of a virus”**. Do you mean your program or something else?
