### ISSUE TITLE
Got Patched I Think

### ISSUE THREAD

**Issue by SatisfactionModder** [Gwyd0/Sparx-bwk#11]
![image](https://github.com/Gwyd0/Sparx-bwk/assets/116923555/23b80359-0924-4428-88dc-aab3340d40e4)
Just Stuck On Blank BW 

I think my problem is that my chrome driver is .90 at the end, not .134 like chrome but i cant find that driver

**Comment by Gwyd0** [comment]
If you didn't answer any questions there is no bookwork codes to log and therefore wont show. Did chrome open when the exe was run?
