### ISSUE TITLE
issues with it working

### ISSUE THREAD

**Issue by mrlewisx67** [Gwyd0/Sparx-bwk#12]
![Screenshot 2023-06-19 183453](https://github.com/Gwyd0/Sparx-bwk/assets/137101734/a5eaba11-3f8c-4e3c-91ee-7a4eeb7b8c9b)

**Comment by emusepass666** [comment]
the same thing happened to me but. it automaticaly exits the file when i opent it.i dont know why and if you have chrome version 120.0.6099.71 you cant download the version that you have its wierd i must say. if you have solutions for me tell me asap
