### ISSUE TITLE
sorry but is there any where to contact you i have alot of questions 

### ISSUE THREAD

**Issue by sayamftw** [Gwyd0/Sparx-bwk#4]

**Comment by Ellirio** [comment]
I would comment on one of the files

**Comment by sayamftw** [comment]
can you make a step by step guide on how to use it?

**Comment by Ellirio** [comment]
I don't know either how to use it LOL tryna reach out but I think you download web driver I think it's linked and then download the files and run them in a code editor like VS Code or Replit where I think you need something to keep it alive like upitimerobot.

**Comment by Ellirio** [comment]
I can't do it cus im not allowed web driver or whatever it was but let me @Gwyd0

**Comment by Gwyd0** [comment]
I have  and created a step by step [guide](https://github.com/Gwyd0/Sparx-bwk#setup-step-by-step
).  And anyone wanting to contact me can do so using discord: Gwyd#9684
