### ISSUE TITLE
i need a step by step guide

### ISSUE THREAD

**Issue by Use-code-F1ZZY** [Gwyd0/Sparx-bwk#6]
mums life somone show me how to do this its too confusing if it acc works mums life ill pay u

**Comment by Deen21109** [comment]
same

**Comment by pwengiun** [comment]
real

**Comment by Gwyd0** [comment]
I will make a step by guide later today on the readme. I didnt really plan on other people using it lmao.

**Comment by Gwyd0** [comment]
I have created a step by step [guide](https://github.com/Gwyd0/Sparx-bwk#setup-step-by-step
).
