### ISSUE TITLE
How to put your school

### ISSUE THREAD

**Issue by pwengiun** [Gwyd0/Sparx-bwk#7]
When I copy the auth on line 124 of Chrome_SPARXBWK.py it says its trying to sign me in to Holsworthy Community College. How could I change this to my school so it works. Thanks

**Comment by Gwyd0** [comment]
Working on a fix should be finished by today.

**Comment by Gwyd0** [comment]
I have fixed this issue with the latest version and created a step by step [guide](https://github.com/Gwyd0/Sparx-bwk#setup-step-by-step
).

**Comment by pwengiun** [comment]
Hello it works now thanks for helping :)
