### ISSUE TITLE
Getting issue on launch

### ISSUE THREAD

**Issue by hfoiy** [Gwyd0/Sparx-bwk#8]
ERROR:device_event_log_impl.cc(222)] [20:29:09.946] USB: usb_device_handle_win.cc:1046 Failed to read descriptor from node connection: A device attached to the system is not functioning. (0x1F)
ERROR:device_event_log_impl.cc(222)] [20:29:09.958] USB: usb_device_handle_win.cc:1046 Failed to read descriptor from node connection: A device attached to the system is not functioning. (0x1F)

**Comment by hfoiy** [comment]
![image](https://user-images.githubusercontent.com/105818298/235767061-d6b36f9b-357e-4ed8-8c47-c8d0ad1db453.png)

I get those errors then the program fails to work

(blurred out possible information)

**Comment by Gwyd0** [comment]
This seems to be a problem with USB drives (which is weird) and shouldn't affect the programme. I will work on this later. For now, I recommend following the [guide](https://github.com/Gwyd0/Sparx-bwk#setup-step-by-step) again. Also, does the programme crash immediately? It seems from the picture that Chrome opens, as it shows the version.

**Comment by exoticusX** [comment]
I also had the same problem 
![image](https://github.com/Gwyd0/Sparx-bwk/assets/121366899/5e49d8cb-00cd-47f5-8b2a-4e41afb4f8d3)

**Comment by Gwyd0** [comment]
I released an update to the chrome version. **Delete** all previous files and try again. Im closing this for now.
